// Led controller states

enum LED_CONTROLLER_STATE{
  LED_STARTUP,
  LED_NORMAL,
  LED_ADD,
  LED_OK,
  LED_FAIL,
  LED_DELETE,
  LED_BADGE_ADDED,
  LED_BADGE_DELETED,
  LED_ERROR
};

enum BadgeType{
 MASTER_BADGE,
 UNKNOWN_BADGE,
 KNOWN_BADGE
};

// Main controller states
enum MAIN_CONTROLLER_STATE{
  STARTUP,
  WAIT_FOR_SCAN_STARTUP,
  WAIT_FOR_SCAN_NORMAL,
  WAIT_FOR_SCAN_ADD,
  WAIT_FOR_SCAN_DELETE,
  ERROR_STATE
};
